-- 001_bronze.sql — immutable, append-only landing zone.
-- Nothing here is ever recomputed. This is the source of truth for actual traded prices.
BEGIN;

CREATE SCHEMA IF NOT EXISTS bronze;
CREATE SCHEMA IF NOT EXISTS silver;
CREATE SCHEMA IF NOT EXISTS gold;
CREATE SCHEMA IF NOT EXISTS ops;

-- ---------------------------------------------------------------- eod_bhav_raw
-- One row per (trade_date, isin, series). ISIN+series is the true natural key:
-- the same ISIN legitimately appears twice in a bhavcopy (e.g. EQ and BE).
CREATE TABLE IF NOT EXISTS bronze.eod_bhav_raw (
    trade_date      date            NOT NULL,
    isin            text            NOT NULL,
    symbol          text            NOT NULL,
    series          text            NOT NULL,
    o               numeric(20,4),
    h               numeric(20,4),
    l               numeric(20,4),
    c               numeric(20,4),
    last_price      numeric(20,4),
    prev_close      numeric(20,4),
    vwap            numeric(20,4),          -- from sec_bhavdata_full AVG_PRICE; else turnover/volume
    volume          bigint,
    turnover        numeric(24,4),          -- rupees (UDiFF TtlTrfVal; legacy TOTTRDVAL)
    trades          bigint,
    deliv_qty       bigint,                 -- sec_bhavdata_full only; NULL pre-2020
    deliv_pct       numeric(9,4),
    price_band      text,                   -- sec_list_<DDMMYYYY>.csv "Band"
    band_remarks    text,
    circuit_flag    boolean,                -- close pinned at a band edge (derived at ingest)
    instrument_type text,                   -- UDiFF FinInstrmTp, e.g. STK
    source_format   text            NOT NULL,   -- 'udiff' | 'legacy'
    source_file     text            NOT NULL,
    row_hash        text            NOT NULL,   -- md5 of canonical payload; detects silent restatements
    ingested_at     timestamptz     NOT NULL DEFAULT now(),
    CONSTRAINT eod_bhav_raw_pk PRIMARY KEY (trade_date, isin, series)
);

CREATE INDEX IF NOT EXISTS eod_bhav_raw_isin_date_idx ON bronze.eod_bhav_raw (isin, trade_date);
CREATE INDEX IF NOT EXISTS eod_bhav_raw_symbol_idx    ON bronze.eod_bhav_raw (symbol, trade_date);
CREATE INDEX IF NOT EXISTS eod_bhav_raw_date_idx      ON bronze.eod_bhav_raw (trade_date);

COMMENT ON TABLE  bronze.eod_bhav_raw IS 'Immutable as-traded EOD bars. Never adjusted. Never deleted.';
COMMENT ON COLUMN bronze.eod_bhav_raw.row_hash IS 'Upsert compares this; a changed hash for an existing key means NSE restated the file and is logged as a restatement.';

-- ------------------------------------------------------------- corp_action_raw
-- Verbatim capture of every corporate-action row the NSE API ever showed us,
-- keyed by WHEN WE SAW IT. Never mutated: this is what makes as-of replay possible.
CREATE TABLE IF NOT EXISTS bronze.corp_action_raw (
    ca_raw_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scrape_date     date            NOT NULL,
    symbol          text,
    isin            text,
    company         text,
    series          text,
    face_value      numeric(20,4),      -- API faceVal; required to price rights (S = FV + premium)
    ex_date         date,
    record_date     date,
    bc_start_date   date,
    bc_end_date     date,
    nd_start_date   date,
    nd_end_date     date,
    ca_broadcast_date date,
    purpose_text    text            NOT NULL,   -- the free-text 'subject' field, verbatim
    payload         jsonb           NOT NULL,   -- whole API row, for forensics
    payload_hash    text            NOT NULL,   -- md5(isin|ex_date|purpose_text|record_date)
    ingested_at     timestamptz     NOT NULL DEFAULT now(),
    -- Same announcement re-scraped daily must not duplicate. Distinct announcements
    -- for the same ISIN+ex_date (compound events) differ in purpose_text, so they survive.
    CONSTRAINT corp_action_raw_uq UNIQUE (payload_hash)
);

CREATE INDEX IF NOT EXISTS corp_action_raw_isin_ex_idx  ON bronze.corp_action_raw (isin, ex_date);
CREATE INDEX IF NOT EXISTS corp_action_raw_scrape_idx   ON bronze.corp_action_raw (scrape_date);

COMMENT ON TABLE bronze.corp_action_raw IS 'Append-only. One row per (announcement, first time seen). payload_hash dedupes daily re-scrapes.';

-- ------------------------------------------------------------- trading_calendar
CREATE TABLE IF NOT EXISTS bronze.trading_calendar (
    cal_date        date        PRIMARY KEY,
    is_trading_day  boolean     NOT NULL,
    reason          text,                       -- holiday description, or 'weekend'
    segment         text        NOT NULL DEFAULT 'CM',
    source          text        NOT NULL,       -- 'nse_holiday_master' | 'weekend_rule' | 'observed_bhavcopy'
    updated_at      timestamptz NOT NULL DEFAULT now()
);
COMMENT ON COLUMN bronze.trading_calendar.source IS
  'observed_bhavcopy = we successfully downloaded a bhavcopy for this date, the strongest possible evidence it traded.';

COMMIT;
