-- 002_silver.sql — parsed, typed, reconciled entities. Rebuildable from bronze alone.
BEGIN;

-- ------------------------------------------------------------- security_master
-- Keyed on ISIN. Delisted names are NEVER removed (survivorship-bias protection).
CREATE TABLE IF NOT EXISTS silver.security_master (
    isin            text        PRIMARY KEY,
    symbol          text        NOT NULL,       -- current / last-known symbol
    name            text,
    series          text,                       -- primary series
    face_value      numeric(20,4),
    listing_date    date,
    delisting_date  date,
    status          text        NOT NULL DEFAULT 'active',   -- active|suspended|delisted
    sector          text,
    symbol_history  jsonb       NOT NULL DEFAULT '[]'::jsonb,
        -- [{"symbol":"MINDTREE","first_seen":"2019-01-01","last_seen":"2023-11-23"}, ...]
    isin_history    jsonb       NOT NULL DEFAULT '[]'::jsonb,   -- ISIN can change on FV split
    first_seen      date,
    last_seen       date,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT security_master_status_ck CHECK (status IN ('active','suspended','delisted'))
);
CREATE INDEX IF NOT EXISTS security_master_symbol_idx ON silver.security_master (symbol);
CREATE INDEX IF NOT EXISTS security_master_status_idx ON silver.security_master (status);

COMMENT ON TABLE silver.security_master IS
  'ISIN is the master key throughout the pipeline. Symbols change (MINDTREE -> LTIM); ISINs are stable.';

-- --------------------------------------------------------- corp_action_event
-- The factor table. One row per ATOMIC, price-relevant event.
-- A single bronze row can fan out to several rows here: the purpose text
-- "AGM/Dividend - Rs 5 Per Share/Special Dividend - Rs 10 Per Share" is three
-- components, of which one adjusts price and two affect the total-return series.
CREATE TABLE IF NOT EXISTS silver.corp_action_event (
    event_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_uid       text        NOT NULL,       -- deterministic md5(isin|ex_date|type|comp_ix|norm_purpose)
    isin            text        NOT NULL,
    symbol          text,
    ex_date         date        NOT NULL,
    record_date     date,
    type            text        NOT NULL,
    -- ratio semantics, by type:
    --   BONUS  : ratio_num new shares FOR ratio_den held
    --            -> shares_before = ratio_den, shares_after = ratio_den + ratio_num
    --   SPLIT  : ratio_num = OLD face value, ratio_den = NEW face value
    --            -> shares_before = ratio_den, shares_after = ratio_num
    --   RIGHTS : ratio_num new shares FOR ratio_den held -> N = ratio_num / ratio_den
    ratio_num       numeric(24,8),
    ratio_den       numeric(24,8),
    sub_price       numeric(20,4),      -- rights ALL-IN subscription price = face_value + premium
    premium         numeric(20,4),      -- as printed, kept for audit
    face_value      numeric(20,4),
    div_amount      numeric(20,6),      -- per-share cash for THIS component
    is_special      boolean     NOT NULL DEFAULT false,

    -- Computed factors. NULL until anchor price P is known (needs the last trading
    -- close strictly before ex_date), which is why factor_state exists.
    factor_price    numeric(24,12),
    factor_vol      numeric(24,12),
    anchor_price    numeric(20,4),      -- P: close on last trading day before ex_date
    anchor_date     date,
    factor_state    text        NOT NULL DEFAULT 'pending',
        -- pending | computed | not_applicable | skipped_s_gt_p | needs_anchor | unresolved

    parsed_ok       boolean     NOT NULL DEFAULT false,
    parser_version  text        NOT NULL,
    confidence      text        NOT NULL DEFAULT 'high',   -- high|medium|low
    component_ix    smallint    NOT NULL DEFAULT 0,        -- position within a compound purpose
    raw_purpose     text        NOT NULL,
    ca_raw_id       bigint      REFERENCES bronze.corp_action_raw(ca_raw_id),
    learned_at      timestamptz NOT NULL DEFAULT now(),    -- as-of reproducibility anchor
    superseded_at   timestamptz,                           -- set if NSE later revised/cancelled
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT corp_action_event_uq UNIQUE (event_uid),
    CONSTRAINT corp_action_event_type_ck CHECK (type IN (
        -- price-adjusting
        'BONUS','SPLIT','FACE_VALUE_CHANGE','RIGHTS','SPECIAL_DIVIDEND','RETURN_OF_CAPITAL',
        -- total-return only (no price adjustment)
        'DIVIDEND','INTERIM_DIVIDEND',
        -- recognised, deliberately NO price effect
        'AGM','EGM','INTEREST_PAYMENT','BUYBACK','NO_ADJUST',
        -- recognised but not computable without external data -> ALSO in review queue
        'DEMERGER','SPINOFF','CAPITAL_REDUCTION','REDEMPTION','SCHEME_OF_ARRANGEMENT',
        'BONUS_PREFERENCE','UNKNOWN'
    )),
    CONSTRAINT corp_action_event_factor_ck CHECK (
        factor_price IS NULL OR (factor_price > 0 AND factor_price <= 1000)
    ),
    CONSTRAINT corp_action_event_state_ck CHECK (factor_state IN (
        'pending','computed','not_applicable','skipped_s_gt_p','needs_anchor','unresolved'
    ))
);

CREATE INDEX IF NOT EXISTS cae_isin_ex_idx    ON silver.corp_action_event (isin, ex_date)
    WHERE superseded_at IS NULL;
CREATE INDEX IF NOT EXISTS cae_ex_date_idx    ON silver.corp_action_event (ex_date);
CREATE INDEX IF NOT EXISTS cae_learned_at_idx ON silver.corp_action_event (learned_at);
CREATE INDEX IF NOT EXISTS cae_state_idx      ON silver.corp_action_event (factor_state)
    WHERE factor_state IN ('pending','needs_anchor','unresolved');

COMMENT ON COLUMN silver.corp_action_event.learned_at IS
  'When this pipeline first computed the event. Filter on it to reconstruct the adjusted panel exactly as it appeared on any past date.';
COMMENT ON COLUMN silver.corp_action_event.type IS
  'BONUS_PREFERENCE is the NCRPS trap: "Bonus Ncrps 1:1" is a bonus of PREFERENCE shares and must NOT rescale the equity price.';
COMMENT ON COLUMN silver.corp_action_event.sub_price IS
  'NSE prints only the PREMIUM ("Rights 1:1 @ Premium Rs 11.25/-"). All-in S = face_value + premium. Verified against 147 real rights rows, incl. "@ Premium Rs 0/-" (issued at par).';

-- ----------------------------------------------------- corp_action_review_queue
-- Anything the parser could not confidently map. Nothing is ever silently dropped.
CREATE TABLE IF NOT EXISTS silver.corp_action_review_queue (
    review_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ca_raw_id       bigint      REFERENCES bronze.corp_action_raw(ca_raw_id),
    isin            text,
    symbol          text,
    ex_date         date,
    raw_purpose     text        NOT NULL,
    reason          text        NOT NULL,
        -- unparsed_pattern | ambiguous_ratio | needs_external_price | s_gt_p
        -- | no_anchor_price | multi_component_partial | implausible_factor
    parser_version  text        NOT NULL,
    suggested_type  text,
    suggested_json  jsonb,                  -- parser best guess, NEVER auto-applied
    severity        text        NOT NULL DEFAULT 'medium',  -- high = price-affecting and unresolved
    status          text        NOT NULL DEFAULT 'open',    -- open|resolved|ignored
    resolution_note text,
    resolved_event_id bigint    REFERENCES silver.corp_action_event(event_id),
    resolved_by     text,
    resolved_at     timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT carq_uq        UNIQUE (ca_raw_id, raw_purpose),
    CONSTRAINT carq_status_ck CHECK (status IN ('open','resolved','ignored')),
    CONSTRAINT carq_sev_ck    CHECK (severity IN ('low','medium','high'))
);
CREATE INDEX IF NOT EXISTS carq_open_idx ON silver.corp_action_review_queue (status, severity)
    WHERE status = 'open';

-- Manual overrides: the human escape hatch. Always wins over the parser.
CREATE TABLE IF NOT EXISTS silver.corp_action_override (
    override_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isin            text        NOT NULL,
    ex_date         date        NOT NULL,
    type            text        NOT NULL,
    factor_price    numeric(24,12),
    factor_vol      numeric(24,12),
    div_amount      numeric(20,6),
    note            text        NOT NULL,
    created_by      text        NOT NULL DEFAULT 'manual',
    created_at      timestamptz NOT NULL DEFAULT now(),
    active          boolean     NOT NULL DEFAULT true,
    CONSTRAINT cao_uq UNIQUE (isin, ex_date, type)
);
COMMENT ON TABLE silver.corp_action_override IS
  'Resolutions for review-queue items and known-bad NSE data. Applied after the parser, before materialization.';

COMMIT;
