-- 004_ops.sql — run ledger, validation findings, and convenience views.
BEGIN;

-- Every CLI invocation writes exactly one row here. This is the operational memory
-- that makes `run-daily` idempotent and auditable.
CREATE TABLE IF NOT EXISTS ops.pipeline_run (
    run_id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_uid         text        NOT NULL UNIQUE,    -- uuid4, echoed into every log line
    command         text        NOT NULL,           -- ingest-eod | run-daily | backfill | ...
    target_date     date,
    started_at      timestamptz NOT NULL DEFAULT now(),
    finished_at     timestamptz,
    status          text        NOT NULL DEFAULT 'running',  -- running|success|warning|failed|skipped
    exit_code       integer,
    -- counters, filled by the run summary
    bhav_rows_ingested      integer DEFAULT 0,
    bhav_rows_restated      integer DEFAULT 0,
    ca_rows_ingested        integer DEFAULT 0,
    ca_events_parsed        integer DEFAULT 0,
    ca_flagged_for_review   integer DEFAULT 0,
    factors_computed        integer DEFAULT 0,
    gold_isins_rebuilt      integer DEFAULT 0,
    gold_rows_written       integer DEFAULT 0,
    alerts_raised           integer DEFAULT 0,
    summary         jsonb,
    error_text      text,
    CONSTRAINT pipeline_run_status_ck CHECK (status IN ('running','success','warning','failed','skipped'))
);
CREATE INDEX IF NOT EXISTS pipeline_run_cmd_date_idx ON ops.pipeline_run (command, target_date DESC);

-- Which (command, date) pairs are already done. The idempotency gate.
CREATE TABLE IF NOT EXISTS ops.run_watermark (
    command         text        NOT NULL,
    target_date     date        NOT NULL,
    status          text        NOT NULL,
    run_id          bigint      REFERENCES ops.pipeline_run(run_id),
    content_hash    text,       -- hash of the source file, so a restated file re-triggers work
    completed_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT run_watermark_pk PRIMARY KEY (command, target_date)
);

-- Validation findings. Persisted so a repeat alert is recognisable as a repeat.
CREATE TABLE IF NOT EXISTS ops.validation_finding (
    finding_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          bigint      REFERENCES ops.pipeline_run(run_id),
    trade_date      date,
    check_name      text        NOT NULL,
        -- prev_close_reconcile | overnight_jump | rowcount_deviation
        -- | unparsed_purpose | missing_symbol | constraint_violation | stale_factor
    severity        text        NOT NULL,       -- info|warning|critical
    isin            text,
    symbol          text,
    detail          text        NOT NULL,
    metrics         jsonb,
    acknowledged    boolean     NOT NULL DEFAULT false,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT validation_finding_sev_ck CHECK (severity IN ('info','warning','critical'))
);
CREATE INDEX IF NOT EXISTS vf_date_check_idx ON ops.validation_finding (trade_date, check_name);
CREATE INDEX IF NOT EXISTS vf_open_idx       ON ops.validation_finding (severity, acknowledged)
    WHERE NOT acknowledged;

-- Rolling expectation for the row-count check, so the norm is data-driven not hardcoded.
CREATE OR REPLACE VIEW ops.v_bhav_rowcount_norm AS
SELECT trade_date,
       cnt,
       avg(cnt) OVER w  AS trailing_avg_20,
       stddev_samp(cnt) OVER w AS trailing_sd_20
FROM (
    SELECT trade_date, count(*)::numeric AS cnt
    FROM bronze.eod_bhav_raw
    GROUP BY trade_date
) t
WINDOW w AS (ORDER BY trade_date ROWS BETWEEN 20 PRECEDING AND 1 PRECEDING);

-- Open, price-affecting parse failures. The single most important operational dashboard:
-- every row here is a symbol whose adjusted history is potentially wrong.
CREATE OR REPLACE VIEW ops.v_open_high_severity_review AS
SELECT q.review_id, q.symbol, q.isin, q.ex_date, q.reason, q.raw_purpose, q.created_at
FROM silver.corp_action_review_queue q
WHERE q.status = 'open' AND q.severity = 'high'
ORDER BY q.ex_date DESC NULLS LAST;

-- Latest bar per ISIN, for freshness checks.
CREATE OR REPLACE VIEW ops.v_symbol_freshness AS
SELECT isin, max(trade_date) AS last_bar, count(*) AS bars
FROM bronze.eod_bhav_raw
GROUP BY isin;

COMMIT;
